model_name: 'exp1'
train: true

env:
  width: 36
  height: 36
  obstacle_prob: 0.0
  perc_range: 5
  max_steps: 50
  render_mode: null
  policy_type: MultiInputPolicy

model:
  policy: MultiInputPolicy
  device: cpu
  learning_rate: 0.0005
  batch_size: 64
  buffer_size: 50000
  exploration_fraction: 0.7
  exploration_final_eps: 0.05
  target_update_interval: 500
  train_freq: 4

wrapper:
  VecTransposeImage: True
  VecNormalize:
    norm_obs: False
    norm_reward: true

training:
  total_timesteps: 1000000