model_name: 'ExplFrontStepEnv_relative_DQN_1e5'
train: true
model_class: 'DQN'
env_class: 'ExplFrontStepEnv'

env:
  height: 20
  width: 20
  obstacle_prob: 0.05
  perc_range: 3
  max_steps: 500
  target_discovery_percent: 0.9
  render_mode: null
  sorting: true
  reverse: false
  relative: true
  

model:
  policy: MultiInputPolicy
  device: cpu
  learning_rate: 0.0005
  batch_size: 64
  buffer_size: 50000
  exploration_fraction: 0.7
  exploration_final_eps: 0.05
  target_update_interval: 500
  train_freq: 4

wrapper:
  VecTransposeImage: False
  VecNormalize:
    norm_obs: True
    norm_reward: true

training:
  total_timesteps: 100000