model_name: 'SimpleTargetAgentEnv_10x10_vectorized_5e5'
train: true
model_class: 'DQN'
env_class: 'SimpleTargetAgentEnv'

env:
  height: 10
  width: 10
  obstacle_prob: 0.0
  max_steps: 250
  render_mode: null
  

model:
  policy: MultiInputPolicy
  device: cpu
  learning_rate: 0.0005
  batch_size: 64
  buffer_size: 50000
  exploration_fraction: 0.7
  exploration_final_eps: 0.05
  target_update_interval: 500
  train_freq: 4

vectorize:
  num_envs: 4

wrapper:
  VecMonitor: true
  DummyVecEnv: true
  VecTransposeImage: false

training:
  total_timesteps: 500000