#!/usr/bin/bash
python3 script_train.py MultiObsFrontierEnv_absolute_iGain_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_absolute_agent_iGain_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_absolute_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_absolute_agent_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_relative_iGain_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_relative_agent_iGain_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_relative_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_relative_agent_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_distance_iGain_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_distance_agent_iGain_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_distance_DQN_1e5
python3 script_train.py MultiObsFrontierEnv_distance_agent_DQN_1e5
