env:
  centroids_obs_len: 10
  height: 20
  max_steps: 500
  obs_spec:
    ag_pos: false
    i_gain: false
    type: distance
  obstacle_prob: 0.05
  perc_range: 3
  render_mode: null
  reverse: true
  sorting: true
  target_discovery_percent: 0.9
  width: 20
env_class: MultiObsFrontAvoidanceEnv
model:
  batch_size: 64
  buffer_size: 50000
  device: cpu
  exploration_final_eps: 0.05
  exploration_fraction: 0.2
  learning_rate: 0.0005
  policy: MlpPolicy
  target_update_interval: 500
  train_freq: 4
  verbose: 0
model_class: DQN
model_name: MultiObsFrontAvoidanceEnv_distance_DQN_dynamic_frac02_2e5_reverse
train: true
training:
  log_interval: 100
  total_timesteps: 200000
wrapper:
  Monitor: true
